### ISSUE TITLE
Search function is not finding anything

### ISSUE THREAD

**Issue by gildedgardenia** [LaunchCodeEducation/csharp-web-development#23]
When searching for words such as "this", "the", "a", and "and", the search function cannot locate anything.

**Comment by CarlyLanglois** [comment]
picked this up for a maintenance task on fri 2/26. The problem here is with "this". The other words are not critical to be searchable but we want students to be able to search for a definition and usage of "this".

It seems that to customize Sphinx search we have two options:
1. add a sphinx extension or
2. configure an external search module, like adding google search

1 would be less of a life but would require a dependency to keep track of and 2 is beyond the scope I want to dedicate to this right now. 

The silver lining with "this" is that a search of "this keyword" will return the right index entry, and "this" is locatable in the index page. 

I'm going to close this for now since we won't be addressing it in the near future.
