### ISSUE TITLE
Class Diagrams

### ISSUE THREAD

**Issue by scottkuhl** [LaunchCodeEducation/csharp-web-development#81]
https://education.launchcode.org/csharp-web-development/chapters/inheritance/class-diagrams.html

Should this chapter include some information on how to install the Class Diagram component in Visual Studio?  I at least a mention that it is not included in any workload install by default anymore and would need to be added manually.

I ask because this came up in the last class.

**Comment by jimflores5** [comment]
As always, thanks for the feedback.

Microsoft provides documentation for "How to: Add class diagrams to projects", but that page concludes with "Class Designer is not available in .NET Core projects."

Rather than dealing with configuring Visual Studio and writing instructions for using the embedded designer (or other electronic option), we opted to stick with pencil and paper.  ;-)

I'll add an extra admonition box to the page to call this out more explicitly.
